#!/bin/bash
# Quick Maven Commands Reference

echo "╔════════════════════════════════════════════════════════════╗"
echo "║          Maven Lifecycle Stages - Quick Reference          ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""
echo "Individual Stages:"
echo "  1. mvn validate    → Validate project structure"
echo "  2. mvn compile     → Compile source code"
echo "  3. mvn test        → Run unit tests"
echo "  4. mvn package     → Create JAR file"
echo "  5. mvn verify      → Run integration tests"
echo "  6. mvn install     → Install to local repository"
echo "  7. mvn deploy      → Deploy to remote repository"
echo ""
echo "Common Commands:"
echo "  mvn clean verify   → Clean + run all stages through verify"
echo "  mvn clean install  → Clean + run all stages through install"
echo "  mvn clean deploy   → Clean + run ALL lifecycle stages"
echo ""
echo "Run Application:"
echo "  mvn exec:java      → Execute the application"
echo "  java -jar target/hello-maven-1.0-SNAPSHOT.jar"
echo ""
echo "Run Script:"
echo "  ./run-all-stages.sh → Run all stages with detailed output"
echo ""
echo "Documentation:"
echo "  See MAVEN_LIFECYCLE.md for detailed information"
echo ""
